### ISSUE TITLE
Add Makefile to build 32/64 emulator binaries

### ISSUE THREAD

**Issue by cfbolz** [pydrofoil/pydrofoil#17]
- [x] Create a Makefile that will provide the chain to build Pydrofoil (matti)
  - [x] restructure the repo a little bit (carl)
  - [x] Add it to the github repo 
  - [x] Pull a PyPy2 for building from downloads.python.org/pypy/
  - [x] Build the 32/64 bit versions of Pydrofoil

**Comment by cfbolz** [comment]
I changed the repo structure in #21 to have a toplevel riscv/ directory.

**Comment by mattip** [comment]
Maybe a flag to toggle between them so we only build once?

**Comment by cfbolz** [comment]
all done now
