### ISSUE TITLE
Make CI build binaries and run the risc-v test suite

### ISSUE THREAD

**Issue by cfbolz** [pydrofoil/pydrofoil#18]
- [x] make CI job build binaries using the Makefile
- [x] Upload the binaries as a release to github
- [x] find out how to execute the risc-v test binaries
  - [x] how annoying is building them?
  - [x] choices: qemu or cross-compiling
  - [ ] add the test runs to CI 
- [ ] if we have time: run the tests on the standard risc-v-sail-emulator

**Comment by cfbolz** [comment]
I added a CI step that builds a pydrofoil binary in #22. using CPython and no makefile. it takes a pretty long time to build, so we should switch to pypy before merging.

I also looked briefly into cross-compiling the risc-v test binaries. it doesn't completely work, but I managed to get pretty far using the `gcc-riscv64-unknown-elf` package on ubuntu.

**Comment by cfbolz** [comment]
pypy works too, I merged

**Comment by mattip** [comment]
In order to setup tests, I did (from the pydrofoil checkout)
```
$ git clone https://github.com/riscv/riscv-tests
$ git submodule update --init --recursive
$ sudo apt install gcc-riscv64-unknown-elf
$ autoconf
$ ./configure   # --prefix=$RISCV/target ??
# Edit the Makefile and remove this line `$(1)_tests += $$($(1)_v_tests)` to avoid the `/v/*` files (virtual memory enabled needs some gcc stdlib support)
$ make    see the debian bug[1] but builds what we need
```

We should add in a link to the tests' documentation https://github.com/riscv-software-src/riscv-tests#readme

[1] ](https://linux.debian.bugs.dist.narkive.com/OZN3UdMP/bug-979542-gcc-riscv64-unknown-elf-unable-to-use-stdint-h)

Maybe we can use prebuilt toolchains from https://github.com/riscv-collab/riscv-gnu-toolchain/releases

**Comment by mattip** [comment]
Then downloading pydrofoil-rscv64 (from the action artifact) and running it on the tests gives [some results](https://gist.github.com/mattip/42c9763057d4d3a71b878655bb4c09cc)

**Comment by cfbolz** [comment]
I tried the action artifact to see how to get the `-v-` files to work. changing `-mabi=lp64` to `-mabi=lp64d` in the makefile makes it build the `-v-` binaries, and they run on pydrofoil afterwards.

**Comment by mattip** [comment]
Still TBD: the tests download a 64-bit toolchain, what do we do with building the 32-bit tests?

**Comment by mattip** [comment]
> what do we do with building the 32-bit tests

We leave that as an exercise for the user. We can download binary versions of the tests from the sail repo

**Comment by mattip** [comment]
I think we can close this as finished?

**Comment by cfbolz** [comment]
we don't run the binary tests in CI yet. should be easy now that Bill said we should just use their pre-built ones. I can take care of it.

**Comment by cfbolz** [comment]
It works! https://github.com/pydrofoil/pydrofoil/actions/runs/3686807202

Closing the issue
