### ISSUE TITLE
Document how to change the ISA model

### ISSUE THREAD

**Issue by mattip** [pydrofoil/pydrofoil#25]
Use case: you have a checkout of the riscv sail repo, and now want to use pydrosail to emulate the ISA model assuming you know how to edit the model
Write a script that
- checkout pypy
- checkout pydrofoil (this repo)
- compile the intermediate representation with sail (one line call to sail)
- builds the emulator around that IR
Running the tests is on the user.

**Comment by mattip** [comment]
To get sail:
- clone https://github.com/riscv/sail-riscv 
- install opam and initialize it with `opam init; opam install sail` (maybe need to do `eval $(opam env)`)
- make

**Comment by cfbolz** [comment]
here's how to do step three, compile the IR with sail.

**64bit version**:

`$ sail -dno_cast -O -Oconstant_fold -memo_z3 -ir -c_include riscv_prelude.h -c_include riscv_platform.h -c_no_main model/prelude.sail model/prelude_mapping.sail model/riscv_xlen64.sail model/riscv_flen_D.sail model/prelude_mem_metadata.sail model/prelude_mem.sail model/riscv_types_common.sail model/riscv_types_ext.sail model/riscv_types.sail model/riscv_vmem_types.sail model/riscv_reg_type.sail model/riscv_freg_type.sail model/riscv_regs.sail model/riscv_pc_access.sail model/riscv_sys_regs.sail model/riscv_pmp_regs.sail model/riscv_pmp_control.sail model/riscv_ext_regs.sail model/riscv_addr_checks_common.sail model/riscv_addr_checks.sail model/riscv_misa_ext.sail model/riscv_csr_map.sail model/riscv_next_regs.sail model/riscv_sys_exceptions.sail model/riscv_sync_exception.sail model/riscv_next_control.sail model/riscv_softfloat_interface.sail model/riscv_fdext_regs.sail model/riscv_fdext_control.sail model/riscv_csr_ext.sail model/riscv_sys_control.sail model/riscv_platform.sail model/riscv_mem.sail model/riscv_pte.sail model/riscv_ptw.sail model/riscv_vmem_common.sail model/riscv_vmem_tlb.sail model/riscv_vmem_sv39.sail model/riscv_vmem_sv48.sail model/riscv_vmem_rv64.sail model/riscv_types_kext.sail model/riscv_insts_begin.sail model/riscv_insts_base.sail model/riscv_insts_aext.sail model/riscv_insts_cext.sail model/riscv_insts_mext.sail model/riscv_insts_zicsr.sail model/riscv_insts_next.sail model/riscv_insts_hints.sail model/riscv_insts_fext.sail model/riscv_insts_cfext.sail model/riscv_insts_dext.sail model/riscv_insts_cdext.sail model/riscv_insts_zba.sail model/riscv_insts_zbb.sail model/riscv_insts_zbc.sail model/riscv_insts_zbs.sail model/riscv_insts_zfh.sail model/riscv_insts_zkn.sail model/riscv_insts_zks.sail model/riscv_insts_zbkb.sail model/riscv_insts_zbkx.sail model/riscv_jalr_seq.sail model/riscv_insts_end.sail model/riscv_step_common.sail model/riscv_step_ext.sail model/riscv_decode_ext.sail model/riscv_fetch.sail model/riscv_step.sail model/riscv_analysis.sail model/main.sail -o generated_definitions/c/riscv_model_RV64`

the output will then be in `generated_definitions/c/riscv_model_RV64.ir` and needs to be put into `pydrofoil/riscv/`

**32 bit version:**

`time sail -dno_cast -O -Oconstant_fold -memo_z3 -ir -c_include riscv_prelude.h -c_include riscv_platform.h -c_no_main model/prelude.sail model/prelude_mapping.sail model/riscv_xlen32.sail model/riscv_flen_D.sail model/prelude_mem_metadata.sail model/prelude_mem.sail model/riscv_types_common.sail model/riscv_types_ext.sail model/riscv_types.sail model/riscv_vmem_types.sail model/riscv_reg_type.sail model/riscv_freg_type.sail model/riscv_regs.sail model/riscv_pc_access.sail model/riscv_sys_regs.sail model/riscv_pmp_regs.sail model/riscv_pmp_control.sail model/riscv_ext_regs.sail model/riscv_addr_checks_common.sail model/riscv_addr_checks.sail model/riscv_misa_ext.sail model/riscv_csr_map.sail model/riscv_next_regs.sail model/riscv_sys_exceptions.sail model/riscv_sync_exception.sail model/riscv_next_control.sail model/riscv_softfloat_interface.sail model/riscv_fdext_regs.sail model/riscv_fdext_control.sail model/riscv_csr_ext.sail model/riscv_sys_control.sail model/riscv_platform.sail model/riscv_mem.sail model/riscv_pte.sail model/riscv_ptw.sail model/riscv_vmem_common.sail model/riscv_vmem_tlb.sail model/riscv_vmem_sv32.sail model/riscv_vmem_rv32.sail model/riscv_types_kext.sail model/riscv_insts_begin.sail model/riscv_insts_base.sail model/riscv_insts_aext.sail model/riscv_insts_cext.sail model/riscv_insts_mext.sail model/riscv_insts_zicsr.sail model/riscv_insts_next.sail model/riscv_insts_hints.sail model/riscv_insts_fext.sail model/riscv_insts_cfext.sail model/riscv_insts_dext.sail model/riscv_insts_cdext.sail model/riscv_insts_zba.sail model/riscv_insts_zbb.sail model/riscv_insts_zbc.sail model/riscv_insts_zbs.sail model/riscv_insts_zfh.sail model/riscv_insts_zkn.sail model/riscv_insts_zks.sail model/riscv_insts_zbkb.sail model/riscv_insts_zbkx.sail model/riscv_jalr_seq.sail model/riscv_insts_end.sail model/riscv_step_common.sail model/riscv_step_ext.sail model/riscv_decode_ext.sail model/riscv_fetch.sail model/riscv_step.sail model/main.sail -o generated_definitions/c/riscv_model_RV32`

the output will then be in `generated_definitions/c/riscv_model_RV32.ir`

**Comment by cfbolz** [comment]
I've written a script that does this and I have set up a [CI workflow](https://github.com/pydrofoil/pydrofoil/actions/workflows/oneshot-script.yml) that tests it by starting just from a sail-riscv repo.

Unfortunately I have discovered in the process that the new Sail version 0.15 breaks Pydrofoil's workflow by removing the commandline option that we have been using. I've opened [an issue](https://github.com/rems-project/sail/issues/190) to try to find out what the plan is. For now I have pinned 0.14 in the workflow.

I should add a test for the correct Sail version in the `Makefile` to give a clear error.

**Comment by mattip** [comment]
Is there a stability statement regarding the IR (jib) language? If it is "stable enough" maybe 0.15 and 0.14 emit equivalent IR.

**Comment by cfbolz** [comment]
I am closing this. it has a CI check, we documented 0.14, the script works.
