### ISSUE TITLE
Put Links into ReadMe

### ISSUE THREAD

**Issue by JonnyWalker** [pydrofoil/pydrofoil#3]
sail etc

**Comment by cfbolz** [comment]
these are the links we used to get sail running under WSL: https://www.cs.umd.edu/class/spring2018/cmsc330/ocamlInstallationGuide.pdf and https://stackoverflow.com/questions/54987110/installing-ocaml-on-windows-10-using-wsl-ubuntu-problems-with-bwrap-bubblewr
