### ISSUE TITLE
Support Sail 0.15

### ISSUE THREAD

**Issue by cfbolz** [pydrofoil/pydrofoil#31]
Sail 0.15 changed the ir text format a little bit and moved the code out from the sail repo into a plugin, see this issue: https://github.com/rems-project/sail/issues/190

we need to adapt to the changes in the text format and the fact that the plugin needs an extra installation step.

**Comment by mattip** [comment]
I am confused about sail https://github.com/rems-project/sail vs sail-riscv https://github.com/riscv/sail-riscv. The former is the one with the 0.15 version, the latter is the one specific to riscv? We seem to reference both in the [building page](https://docs.pydrofoil.org/en/latest/building_pydrofoil.html)

**Comment by cfbolz** [comment]
now that #54 is merged we can close this :tada:
