### ISSUE TITLE
toward multi-platform support

### ISSUE THREAD

**Issue by mattip** [pydrofoil/pydrofoil#38]
The Makefile should check the output of `uname -m` since only x86_64 is currently supported. It would be nice to use that output to build pydrofoil-riscv for other machine architectures supported by RPython

**Comment by cfbolz** [comment]
ok, will look into it (linux arm support shouldn't be super hard, honestly). I might also try to get a WSL CI job going.

**Comment by cfbolz** [comment]
I think we can close this, the macOS part works.
