### ISSUE TITLE
Support for Sail's Real type

### ISSUE THREAD

**Issue by cfbolz** [pydrofoil/pydrofoil#53]
One of the missing features we know we are going to need for the ARM Sail model is Sail's Real type. Real numbers are supposed to represent abstract mathematical real numbers, but in practice the C backend of Sail implements them as fractions. At the moment Pydrofoil does not support that type, we need to fix that.

Here are some steps how that work could proceed:
- write some small example Sail programs that use the Real type and performs some operations on Real numbers
- translate the program to JIB and adding the program as a new integration test to the pydrofoil test suite.
- start implementing the Real type and the operations on them. The Real type implementation should go into a new file `pydrofoil/real.py`. The Real type should use the `rpython.rlib.rbigint.rbigint` class for both the numerator and the denominator values and should use naive school fraction arithmetic (later we will have to implement a more efficient representation of Reals, but we should start with this general one).
- particular attention needs to be put on the testing strategy for the operations on the real type. We need some hand-written unit tests with example values, but should also write property-based tests using [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) to catch corner cases.

Here's the list of operations on the Real type that sail supports:
    - `val "neg_real" : real -> real`
    - `val "mult_real" : (real, real) -> real`
    - `val "sub_real" : (real, real) -> real`
    - `val "add_real" : (real, real) -> real`
    - `val "div_real" : (real, real) -> real`
    - `val sqrt = pure "sqrt_real" : real -> real`
    - `val "abs_real" : real -> real`
    - `val floor = pure "round_down" : real -> int`
    - `val ceil = pure "round_up" : real -> int`
    - `val "to_real" : int -> real`
    - `val "eq_real" : (real, real) -> bool`
    - `val "lt_real" : (real, real) -> bool`
    - `val "gt_real" : (real, real) -> bool`
    - `val "lteq_real" : (real, real) -> bool`
    - `val "gteq_real" : (real, real) -> bool`
    - `val pow_real = pure "real_power" : (real, int) -> real`
    - `val "print_real" : (string, real) -> unit`
    - `val "prerr_real" : (string, real) -> unit`
    - `val "random_real" : unit -> real`

**Comment by Jubo-Xu** [comment]
hello, I think I could have a try of this, I would start from the first step, the change of parser would be considered at step 3 right?

**Comment by Jubo-Xu** [comment]
[https://gist.github.com/Jubo-Xu/b4119d1dbef3fa04690efe9fee2cfb7d](url) gist of simple real-type arithmetic operation test and its JIB file

**Comment by cfbolz** [comment]
now that #56 is merged, this is mostly done. the only place where we cheated is `sqrt_real` which is not correctly implemented yet. I will leave the issue open for that.

**Comment by cfbolz** [comment]
some information about `sqrt_real`:

The C implementation that Sail uses is [here](https://github.com/rems-project/sail/blob/sail2/lib/sail.c#L1327). They are using [Heron's method](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Heron's_method) to approximate the result.

Here's an integer sqrt implementation for rbigints that you can use in the implementation:

```python
    def isqrt(self):
        """ Compute the integer square root of self """
        if self.int_lt(0):
            raise ValueError("isqrt() argument must be nonnegative")
        if self.int_eq(0):
            return NULLRBIGINT
        c = (self.bit_length() - 1) // 2
        a = ONERBIGINT
        d = 0
        for s in range(bits_in_digit(_store_digit(c)) - 1, -1, -1):
            # Loop invariant: (a-1)**2 < (self >> 2*(c - d)) < (a+1)**2
            e = d
            d = c >> s
            a = a.lshift(d - e - 1).add(self.rshift(2*c - e - d + 1).floordiv(a))
        return a.int_sub(a.mul(a).gt(self))

```

**Comment by cfbolz** [comment]
#60 also fixed `sqrt`, I'm closing this.
